### ISSUE TITLE
wifi support

### ISSUE THREAD

**Issue by phpaiva** [evanslai/pyieee1905#1]
There is any way to use the existing WiFi connection (using the current BSSID association) to send CMDUs to an specific MAC address of the LAN?

Thanks!

**Comment by evanslai** [comment]
My method is as follows:

```
# Generate the packet
p = Ether(type=0x893a, src="xx:xx:xx:xx:xx:xx", dst="yy:yy:yy:yy:yy:yy")/msg/tlv/b"\x00\x00\x00"
```

Where `xx:xx:xx:xx:xx:xx` is your wifi mac and `yy:yy:yy:yy:yy:yy` is your specific mac address of the LAN.

```
# Send the packet
sendp(p, iface="en0")
```
Where `en0` is my WiFi interface.

**Comment by phpaiva** [comment]
It worked, thank you very much!
