### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by SimonTate** [evanslai/pyieee1905#3]
Hi,

Firstly, thanks for this - and for leaving this public! It's really helped us out with using 1905.

Just wondering if this project is still active and ok to be maintained or should we create a fork for any fixes?

Thanks,
Simon

**Comment by evanslai** [comment]
Hi Simon,

I do not have any plans for this project.
I just use this repo to record my work.
You can copy it to create a new project.

Thanks.
Evan
